admin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'), name='users'),
    path('regist/', include('regist.urls'), name='regist'),
]

regist/urls.py
from django.urls import path
from . import views

app_name = 'regist'

urlpatterns = [
    path('sublist/', views.sublist, name='sublist'),
    path('enroll/<str:sub_id>', views.enroll, name='enroll'),
    
]

users/urls.py
from django.urls import path
from . import views

app_name ='users'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('remove/<str:sub_id>', views.remove, name='remove'),
]   

regist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    s_id = models.PositiveIntegerField()
    
    def __str__(self):
        return f'ID: {self.s_id} ,Username {self.user.username}'
    
class Subject(models.Model):
    sub_id = models.CharField(max_length=5, primary_key='True')
    sub_name = models.CharField(max_length=64)
    capacity  = models.PositiveIntegerField()
    status = models.BooleanField()
    semester = models.PositiveIntegerField()
    year = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.sub_id} {self.sub_name}'

class SubjectStudentList(models.Model):
    subject = models.OneToOneField(Subject, on_delete=models.CASCADE, primary_key=True)
    students = models.ManyToManyField(Student, blank=True)
    
    def __str__(self):
        return f'{self.subject.sub_id} {self.subject.sub_name}'

users/models.py
from django.db import models

# Create your models here.

regist/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from regist.models import Student, Subject, SubjectStudentList

# Create your views here.

def sublist(request):
    student = Student.objects.get(user_id=request.user)
    subjects = Subject.objects.all()
    data = {'student': student, 
            'subjects': subjects}
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))
    return render(request, 'sublist.html', data)

def enroll(request, sub_id):
    student = Student.objects.get(user_id=request.user)
    sublist = SubjectStudentList.objects.get(subject_id=sub_id)
    sublist.students.add(student)

    subj = Subject.objects.get(sub_id=sub_id)
    subj.capacity -= 1
    if subj.capacity < 0:
        return render(request, 'sublist.html')
    subj.save()
    
    return HttpResponseRedirect(reverse('users:index'))

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from regist.models import Student, Subject, SubjectStudentList

# Create your views here.

def index(request):
    student = Student.objects.get(user_id=request.user)
    subjects = SubjectStudentList.objects.all()

    mysubject = []
    for subject in subjects:
        if student in subject.students.all():
            mysubject.append(subject)

    data = {'student': student, 
            'subjects': mysubject}
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))
    return render(request, 'index.html', data)

def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('users:index'))
        else:
            return render(request, 'login.html', {
                'message': 'Invalid credentials.'
            })

    return render(request, 'login.html')

def logout_view(request):
    logout(request)
    return render(request, 'login.html', {
        'message': 'Logged out'
    })

def remove(request, sub_id):
    student = Student.objects.get(user_id=request.user)
    sublist = SubjectStudentList.objects.get(subject_id=sub_id)
    sublist.students.remove(student)
    
    subj = Subject.objects.get(sub_id=sub_id)
    subj.capacity += 1
    if subj.capacity < 0:
        return render(request, 'sublist.html')
    subj.save()
    
    return HttpResponseRedirect(reverse('users:index'))

regist/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

regist/templates/sublist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>student home page</title>
    <style>
        * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: "Poppins",sans-serif ;} 
    table {
        width: 100%;
    }
    th {
        height: 30px;
        border: transparent;
        border-collapse: collapse;
        border-radius: 10px;
    }
    td {
        height: 50px;
        border: transparent;
        border-collapse: collapse;
        margin: 20px;
    }    
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        background: url(https://scontent.fbkk6-2.fna.fbcdn.net/v/t1.6435-9/126241817_2784599285144060_6235241575451976301_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=730e14&_nc_ohc=a1JnMY5ndv0AX_8v_y8&_nc_ht=scontent.fbkk6-2.fna&oh=00_AfAeCyU9zqt1GsqGxPAbKRsN7z6QxoQW5Ln9T2Buyc-V1w&oe=6548F25B);
        background-size: cover;
        background-position: center;
        padding: 50px;
    }
    
    .wrapper {
        width: 700px;
        background: rgba(231, 245, 231, 0.945);
        border: 2px solid rgba(255, 255, 255, .2);
        backdrop-filter: blur(60px);
        box-shadow:0 0 10px rgba(0, 0, 0, .2) ;
        color:black;
        border-radius: 10px;
        padding: 30px 40px;
    }
    </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div class="wrapper">
    {% extends 'layout.html' %}
    {% block body %}

    <h1 style="margin: 0px; padding: 40px; opacity: 85%;"><center>Registrar, {{ student.user.first_name }}</center></h1>
    <h4><center>request quota home page</center></h4>
    
    <br>
    <p style="padding: 20px; background: rgb(199, 226, 186); border-radius: 10px;">
        Username: {{ student.user.username }}<br>
        Student ID: {{student.s_id}}<br>
        Email: {{ student.user.email }}<br>
    </p>
    <br>

    <table>
        <tr style="background: rgb(238, 228, 111);">
            <th><center>Semester</center></th>
            <th><center>Subject</center></th>
            <th><center>Available</center></th>
            <th><center>Status</center></th>
        </tr>
        {% for subject in subjects %}
        <tr style="background:none;">
            <td><center>{{ subject.semester }}/{{ subject.year }}</center></td>
            <td style="text-indent: 20px;"><div>&nbsp;{{ subject }}</td>
            <td><center>{{ subject.capacity }}</center></td>    
            {% if subject.capacity == 0 %}
                <td><center>Not available</center></td>    
            {% else %}
                <td><center><a href="{% url 'regist:enroll' subject.sub_id %}" class="btn btn-default btn-sm" style="background-color: rgb(76, 218, 104); border-color: rgb(76, 218, 104); color: white;">
                    Enroll</a>&nbsp;</center></div></td>
            {% endif %}
        </tr>  
        {% endfor %}
    </table>
    <br>
    <div style="float: bottom;"><center>
        <a href="{% url 'users:index' %}" class="btn btn-info btn-lg" style="background-color: rgb(214, 136, 219); border-color: rgb(112, 198, 251) ; color: white; size: 10%;">
        <span class="glyphicon glyphicon-home"></span>&nbsp;Back to home</a>
    </center></div>
    {% endblock %}
</div>
</body>
</html>

users/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>student home page</title>
        <style>
            * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: "Poppins",sans-serif ;} 
            table {
                width: 100%;
            }
            th {
                height: 30px;
                border: transparent;
                border-collapse: collapse;
                border-radius: 10px;
            }
            td {
                height: 50px;
                border: transparent;
                border-collapse: collapse;
                margin: 20px;
            }
        
            body {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        background: url(https://scontent.fbkk6-2.fna.fbcdn.net/v/t1.6435-9/126860888_2784600101810645_7728869971705722271_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=730e14&_nc_ohc=F1JS2Pyo30IAX_DuXiK&_nc_ht=scontent.fbkk6-2.fna&oh=00_AfA8O0bm18VHAM7SpP7JCSue8XB9PgRvVfUwUgft4shsXg&oe=6548F7CD);
        background-size: cover;
        background-position: center;
        padding: 50px;
    }
    
    .wrapper {
        width: 700px;
        background: whitesmoke;
        border: 2px solid rgba(255, 255, 255, .2);
        backdrop-filter: blur(60px);
        box-shadow:0 0 10px rgba(0, 0, 0, .2) ;
        color:black;
        border-radius: 10px;
        padding: 30px 40px;
        opacity: 95%;
    }
        </style>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
<body>
{% extends 'layout.html' %}
{% block body %}
<div class="wrapper">
    <h1 style="background: whitesmoke; margin: 0px; padding: 40px; border-radius: 10px; opacity: 100%;">
        <center>Welcome, {{ student.user.first_name }} !</center></h1>
    <br>
    <p style="padding: 20px; background: rgb(199, 226, 186); border-radius: 10px;">
        Username: {{ student.user.username }}<br>
        Student ID: {{student.s_id}}<br>
        Email: {{ student.user.email }}<br>
    </p>
    <br>
    <table>
        <tr style="background: rgb(238, 228, 111);">
            <th><center>Quota Requested</center></th>
            <th><center>Status</center></th>
        </tr>
        {% for subject in subjects %}
        <tr style="background: white; ">
            <td style="text-indent: 20px;";>&nbsp;{{ subject }}</td>
            <td><center><a href="{% url 'users:remove' subject.subject_id %}" class="btn btn-default btn-sm" 
                style="background-color: rgb(251, 112, 147); border-color: rgb(251, 112, 147) ; color: white; border-radius: 30px;" >
                <span class="glyphicon glyphicon-remove"></span>&nbsp;Drop</a></center></td>
            {% endfor %}
        </tr>
        </table>
        <br>
        <div style="float: bottom;"><center>
            <a href="{% url 'regist:sublist' %}" class="btn btn-info btn-lg" style="background-color: rgb(112, 198, 251); border-color: rgb(112, 198, 251) ; color: white; size: 10%;">
                <span class="glyphicon glyphicon-edit"></span>&nbsp;Request Quota</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="{% url 'users:logout' %}" class="btn btn-info btn-lg" style="background-color: rgb(246, 100, 60); border-color: rgb(246, 100, 60) ; color: white;">
                <span class="glyphicon glyphicon-log-out"></span>&nbsp;Log out</a>
        
        </center></div>
    {% endblock %}
</div>
</body>
</html>

users/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <title>login Quota</title>
    <link rel = "stylesheet" href="style.css">

    <style>
     * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: "Poppins",sans-serif ;
}

body {
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    background: url(https://med.engr.tu.ac.th/images/webpage/230420144225_02021.7.12_210712_9_.jpg);
    background-size: cover;
    background-position: center;
}

.wrapper {
    width: 420px;
    background: rgba(226, 252, 253, 0.945);
    border: 2px solid rgba(255, 255, 255, .2);
    backdrop-filter: blur(60px);
    box-shadow:0 0 10px rgba(0, 0, 0, .2) ;
    color:black;
    border-radius: 10px;
    padding: 30px 40px;
}

.wrapper h1 {
    font-size: 20px;
    text-align: center;
}

.wrapper .input-box {
    position: relative;
    width: 100%;
    height: 50px;
    margin: 30px 0;
}

.input-box input{
    width: 100%;
    height: 100%;
    background: rgb(175, 223, 238);
    border: none;
    outline: none;
    border: 2px solid rgba(255, 255, 255, .2);
    border-radius: 40px;
    font-size: 16px;
    color: black;
    padding: 20px 45px 20px 20px;
}

.input-box input::placeholder{
    color: black;
}
.input-box i{
    position: absolute;
    right: 20px;
    top: 25px;
    transform: translateY(-50%);
    font-size: 20px;
}

.wrapper .btn {
    width: 100%;
    height: 30px;
    background: #fff;
    border: none;
    outline: none;
    border-radius: 40px;
    box-shadow: 0 0 10px rgba(0, 0, 0, .1);
    cursor: pointer;
    font-size: 16px;
    color: #333;
    font-weight: 600;
    margin: 20px 0 15px;
}
    
    </style>
    
</head>
<body>
  <div class="wrapper">
     <h1>Welcome to Registration</h1>
     <h1>please sign in </h1>
     {% extends 'layout.html' %}
     {% block body %}

     {% if message %}
        <div>{{ message }}</div>
     {% endif %}

     <form action="{% url 'users:login' %}" method="post">
     {% csrf_token %}
      <div class="input-box">
        <input type="text" name="username" placeholder="Username" required>
        <i class='bx bx-user'></i>
      </div>

      <div class="input-box">
        <input type="password" name="password" placeholder="Password" required>
        <i class='bx bxs-lock-alt'></i>
      </div>

     <input type="submit" class="btn" value="Login">
     </form>

     {% endblock %}
   </div>
</body>

</html>